apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fd1z
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-fd1z@sha256:a20093b80fafaaca43dc097f7a19baa335706588a9d0169b4421ba0ce6a16063
        name: my-nodejs
        resources: {}
status: {}
